# Generated by Django 3.2.21 on 2023-12-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joulukortti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xmascard',
            name='drawing_url',
        ),
        migrations.AddField(
            model_name='xmascard',
            name='drawing',
            field=models.ImageField(blank=True, null=True, upload_to='xmas_cards/'),
        ),
    ]
