# Generated by Django 3.2.21 on 2023-12-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joulukortti', '0002_auto_20231210_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmascard',
            name='drawing',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
