# Generated by Django 3.2.21 on 2023-12-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joulukortti', '0005_color_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
